create database customer;
use customer;
select * from behaviour_table limit 20;

-- Q1. What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customers_behaviour
group by gender

-- Q2. Which customer used the discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customers_behaviour
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customers_behaviour)

-- Q3. Which are the top 5 product with the highest average review rating?
SELECT item_purchased, ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS `Average Product Rating`
FROM customers_behaviour
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average purchase amounts between standard and express shipping?
select shipping_type,
round(avg(purchase_amount),2)
from customers_behaviour
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subcribers?
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers_behaviour
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. Which 5 product has the highest percentage of purchases with discount applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customers_behaviour
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into new, returning, and loyal on their total number of previous purchases, and show the count of each egment?
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment
from customers_behaviour
)    

select customer_segment, count(*) as 'number of customers'
from customer_type
group by customer_segment
    
 -- Q8. what are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customers_behaviour
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customers_behaviour
where previous_purchases > 5
group by subscription_Status

 -- Q10. What is the revenue contribution of each age group?
 select age_group,
 sum(purchase_amount) as total_revenue
 from customers_behaviour
 group by age_group
 order by total_revenue desc;
